import React from 'react';
import Search from './AlbumSearch';
import Head from 'next/head';

export default function AlbumResults() {
  const [result, setResult] = React.useState();
  const [search, setSearch] = React.useState('');
  React.useEffect(() => {
    console.log('index', search);
    if (search === undefined || search === '') {
      return;
    }
    fetch(
      `https://ws.audioscrobbler.com/2.0/?method=album.search&album=${search}&api_key=e836ddbce95921744c7e9efe110bcd54&format=json`
    )
      .then((res) => res.json())
      .then((data) => {
        console.log('data', data);
        setResult(data.results.albummatches.album);
        return result;
      });
  }, [search]);

  if (result === undefined) {
    return (
      <>
        <Head>
          <title>Mixlist</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <section>
            <Search search={search} setSearch={setSearch} result={result} />
          </section>
        </main>
      </>
    );
  }
  const selectedResults = result.slice(0, 5);
  return (
    <>
      <Head>
        <title>Mixlist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section>
          <Search search={search} setSearch={setSearch} result={result} />
        </section>
        <h1>Search results for {search}</h1>

        <div>
          {selectedResults.map((e) => (
            <div key={`${e.name}`}>
              <img src={`${e.image[2][`#text`]}`} alt="" />

              <p>Name: </p>
              <b>
                <p id="album_name">{e.name}</p>
              </b>

              <i>
                <p id="album_artist">{e.artist}</p>
              </i>
            </div>
          ))}
        </div>
      </main>
    </>
  );
}
