import React from 'react';
import AlbumSearch from './AlbumSearch';
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';

export default function AlbumResults() {
  const [result, setResult] = React.useState();
  const [search, setSearch] = React.useState('');
  React.useEffect(() => {
    console.log('index', search);
    if (search === undefined || search === '') {
      return;
    }
    fetch(
      `https://ws.audioscrobbler.com/2.0/?method=album.search&album=${search}&api_key=e836ddbce95921744c7e9efe110bcd54&format=json`
    )
      .then((res) => res.json())
      .then((data) => {
        console.log('data', data);
        setResult(data.results.albummatches.album);
        return result;
      });
  }, [search]);

  if (result === undefined) {
    return (
      <>
        <Head>
          <title>Mixlist</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <section>
            <AlbumSearch
              search={search}
              setSearch={setSearch}
              result={result}
            />
          </section>
        </main>
      </>
    );
  }
  const selectedResults = result.slice(0, 5);
  return (
    <>
      <Head>
        <title>Mixlist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section>
          <AlbumSearch search={search} setSearch={setSearch} result={result} />
        </section>
        <h1 className="text-WHITE">Search results for {search}</h1>

        <div className="text-WHITE ">
          {selectedResults.map((e) => (
            <div key={`${e.name}`}>
              <img
                src={`${e.image[2][`#text`]}`}
                alt=""
                width="100"
                height="100"
              />

              <p>Name: </p>
              <b>
                <p id="album_name">
                  <Link
                    href="/artists/[name]/[album]"
                    as={`/artists/${e.artist}/${e.name}`}
                  >
                    {e.name}
                  </Link>
                </p>
              </b>

              <i>
                <p id="album_artist">
                  <Link href="/artists/[name]" as={`/artists/${e.artist}`}>
                    {e.artist}
                  </Link>
                </p>
              </i>
            </div>
          ))}
        </div>
      </main>
    </>
  );
}
