import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import React from 'react';
import Search from '../components/Search';

import {
  Input,
  Box,
  Button,
  Flex,
  Menu,
  MenuButton,
  MenuList,
  MenuItem,
  MenuItemOption,
  MenuGroup,
  MenuOptionGroup,
  MenuIcon,
  MenuCommand,
  MenuDivider,
  Heading,
  UnorderedList,
  ListItem,
} from '@chakra-ui/react';
import {
  AddIcon,
  HamburgerIcon,
  ExternalLinkIcon,
  RepeatIcon,
  IconButton,
  EditIcon,
  SearchIcon,
} from '@chakra-ui/icons';
import { render } from 'react-dom';
const url = `https://ws.audioscrobbler.com/2.0/?method=album.search&album=donda&api_key=e836ddbce95921744c7e9efe110bcd54&format=json`;

// export async function getServerSideProps({ req, res }) {
//   return await fetch(url)
//     .then((response) => response.json())
//     .then((data) => {
//       // console.log(data);
//       // const { data, error } = await
//       return {
//         props: {
//           albums: data.results.albummatches.album,
//         },
//       };
//     });
// }
export default function Home() {
  const [result, setResult] = React.useState();
  const [search, setSearch] = React.useState('');
  console.log('search', search);
  React.useEffect(() => {
    console.log('index', search);
    if (search === undefined || search === '') {
      return;
    }
    fetch(
      `https://ws.audioscrobbler.com/2.0/?method=album.search&album=${search}&api_key=e836ddbce95921744c7e9efe110bcd54&format=json`
    )
      .then((res) => res.json())
      .then((data) => {
        console.log('data', data);
        setResult(data.results.albummatches.album);
        return result;
      });
  }, [search]);

  // React.useEffect(() => {
  //   if (result === undefined) {
  //     return;
  //   }
  //   return result;
  // }, [result]);
  console.log('result', result);

  console.log(search);

  // React.useEffect(() => {
  // })

  // React.useEffect(() => {
  //   if (input === undefined) {
  //     return;
  //   }
  //   setInput(input);
  // }, [input]);
  if (result === undefined) {
    return (
      <>
        <Head>
          <title>Mixlist</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <section>
            <Search search={search} setSearch={setSearch} result={result} />
          </section>
        </main>
      </>
    );
  }
  const selectedResults = result.slice(0, 5);
  return (
    <>
      <Head>
        <title>Mixlist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section>
          <Search search={search} setSearch={setSearch} result={result} />
        </section>
        <h1>Search results for {search}</h1>

        <div>
          {selectedResults.map((e) => (
            <div key={`${e.name}`}>
              <img src={`${e.image[2][`#text`]}`} alt="" />

              <p>Name: </p>
              <b>
                <p id="album_name">{e.name}</p>
              </b>

              <i>
                <p id="album_artist">{e.artist}</p>
              </i>
            </div>
          ))}
        </div>
      </main>
    </>
  );
}
