import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import React from 'react';
import {
  Input,
  Box,
  Button,
  Flex,
  Menu,
  MenuButton,
  MenuList,
  MenuItem,
  MenuItemOption,
  MenuGroup,
  MenuOptionGroup,
  MenuIcon,
  MenuCommand,
  MenuDivider,
  Heading,
  UnorderedList,
  ListItem,
} from '@chakra-ui/react';
import {
  AddIcon,
  HamburgerIcon,
  ExternalLinkIcon,
  RepeatIcon,
  IconButton,
  EditIcon,
  SearchIcon,
} from '@chakra-ui/icons';
const url = `https://ws.audioscrobbler.com/2.0/?method=album.search&album=donda&api_key=e836ddbce95921744c7e9efe110bcd54&format=json`;

export async function getServerSideProps({ req, res }) {
  return fetch(url)
    .then((response) => response.json())
    .then((data) => {
      // console.log(data);
      // const { data, error } = await
      return {
        props: {
          albums: data.results.albummatches.album,
        },
      };
    });
}
export default function Home({ albums }) {
  console.log(albums);
  const selectedResults = albums.slice(0, 5);
  const [input, setInput] = React.useState('');
  return (
    <>
      <Head>
        <title>Mixlist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section>
          <h1>Last.fm Testing</h1>

          <p>Search an album</p>

          <form id="albumForm">
            <label htmlFor="album">Album</label>
            <input
              type="text"
              id="album"
              name="album"
              maxLength="20"
              value={input}
              onInput={(e) => setInput(e.target.value)}
              required
            />
            <button type="submit" id="albumSubmit">
              Submit
            </button>
          </form>
        </section>
        <h1>Search results for DONDA</h1>

        <div>
          {selectedResults.map((e) => (
            <div key={`${e.name}`}>
              {/* <Image src={`${e.image[1][`#text`]}`} alt="" /> */}

              <p>Name: </p>
              <b>
                <p id="album_name">{e.name}</p>
              </b>

              <i>
                <p id="album_artist">{e.artist}</p>
              </i>
            </div>
          ))}
        </div>
      </main>
    </>
  );
}
